# Generated by Django 4.0 on 2022-06-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('uid', models.TextField(max_length=100)),
                ('destination', models.TextField(max_length=15)),
            ],
        ),
    ]
